branchName: short
silent: false
defaultBranch: 'development'
autoCloseIssue: true
openDraftPR: true

branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
  - label: '*'
    prefix: issues/
