version: 1.0.{build}_{branch}
configuration: Release
platform: Any CPU
build:
  verbosity: minimal
artifacts:
- path: src\BetterER\bin\$(configuration)
  name: BetterER_NETComponents_$(APPVEYOR_BUILD_VERSION)_{branch}
